//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace ExternalUnionMember
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Cat : Pet
    {
    
        private string _name;
    
        private bool _canMeow;
    
        public Cat()
        {
        }
    
        protected Cat(Cat other) : 
                base(other)
        {
            _name = other._name;
            _canMeow = other._canMeow;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="name")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("can_meow")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="can_meow")]
        public bool CanMeow
        {
            get
            {
                return _canMeow;
            }
            set
            {
                _canMeow = value;
            }
        }
    
        public System.IObservable<Cat> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Cat(this)));
        }
    
        public System.IObservable<Cat> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Cat(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("Name = " + _name + ", ");
            stringBuilder.Append("CanMeow = " + _canMeow);
            return true;
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "pet_type")]
    [YamlDiscriminator("pet_type")]
    [JsonInheritanceAttribute("cat", typeof(Cat))]
    [JsonInheritanceAttribute("dog", typeof(PetDog))]
    public abstract partial class Pet
    {
    
        public static implicit operator Pet(PersonAndDog.Dog value)
        {
            return new PetDog(value);
        }
    
        protected Pet()
        {
        }
    
        protected Pet(Pet other)
        {
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return false;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(JsonUnionWrapperConverter), typeof(PersonAndDog.Dog), "pet_type", "dog")]
    [YamlUnionWrapper(typeof(PersonAndDog.Dog))]
    internal sealed partial class PetDog : Pet, IUnionWrapper, IUnionWrapper<PersonAndDog.Dog>
    {
    
        private PersonAndDog.Dog _value;

        private PetDog()
        {
        }

        internal PetDog(PersonAndDog.Dog value)
        {
            _value = value;
        }

        public PersonAndDog.Dog Value
        {
            get { return _value; }
        }

        object IUnionWrapper.Value
        {
            get { return _value; }
            set { _value = (PersonAndDog.Dog)value; }
        }

        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("Value = " + _value);
            return true;
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class PersonAndPet
    {
    
        private string _owner;
    
        private Pet _pet;
    
        public PersonAndPet()
        {
        }
    
        protected PersonAndPet(PersonAndPet other)
        {
            _owner = other._owner;
            _pet = other._pet;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("owner")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="owner")]
        public string Owner
        {
            get
            {
                return _owner;
            }
            set
            {
                _owner = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("pet")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="pet")]
        public Pet Pet
        {
            get
            {
                return _pet;
            }
            set
            {
                _pet = value;
            }
        }
    
        public System.IObservable<PersonAndPet> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new PersonAndPet(this)));
        }
    
        public System.IObservable<PersonAndPet> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new PersonAndPet(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Owner = " + _owner + ", ");
            stringBuilder.Append("Pet = " + _pet);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; private set; }

        public System.Type Type { get; private set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public class JsonInheritanceConverter : Newtonsoft.Json.JsonConverter
    {
        internal static readonly string DefaultDiscriminatorName = "discriminator";

        private readonly string _discriminatorName;

        [System.ThreadStatic]
        private static bool _isReading;

        [System.ThreadStatic]
        private static bool _isWriting;

        public JsonInheritanceConverter()
        {
            _discriminatorName = DefaultDiscriminatorName;
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            try
            {
                _isWriting = true;

                var jObject = Newtonsoft.Json.Linq.JObject.FromObject(value, serializer);
                jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(_discriminatorName, GetSubtypeDiscriminator(value.GetType())));
                writer.WriteToken(jObject.CreateReader());
            }
            finally
            {
                _isWriting = false;
            }
        }

        public override bool CanWrite
        {
            get
            {
                if (_isWriting)
                {
                    _isWriting = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanRead
        {
            get
            {
                if (_isReading)
                {
                    _isReading = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanConvert(System.Type objectType)
        {
            return true;
        }

        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var jObject = serializer.Deserialize<Newtonsoft.Json.Linq.JObject>(reader);
            if (jObject == null)
                return null;

            var discriminatorValue = jObject.GetValue(_discriminatorName);
            var discriminator = discriminatorValue != null ? Newtonsoft.Json.Linq.Extensions.Value<string>(discriminatorValue) : null;
            var subtype = GetObjectSubtype(objectType, discriminator);

            var objectContract = serializer.ContractResolver.ResolveContract(subtype) as Newtonsoft.Json.Serialization.JsonObjectContract;
            if (objectContract == null || System.Linq.Enumerable.All(objectContract.Properties, p => p.PropertyName != _discriminatorName))
            {
                jObject.Remove(_discriminatorName);
            }

            try
            {
                _isReading = true;
                return serializer.Deserialize(jObject.CreateReader(), subtype);
            }
            finally
            {
                _isReading = false;
            }
        }

        private System.Type GetObjectSubtype(System.Type objectType, string discriminator)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Key == discriminator)
                    return attribute.Type;
            }

            return objectType;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return objectType.Name;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Combinator)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Cat>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PersonAndDog.Dog>))]
    public partial class MatchPet : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = Type;
            var source = System.Linq.Enumerable.First(arguments);
            var inputType = source.Type.GetGenericArguments()[0];
            var elementType = inputType;
            var returnType = typeMapping != null ? typeMapping.GetType().GetGenericArguments()[0] : typeof(Pet);
            if (!elementType.IsInterface && !elementType.IsAssignableFrom(typeof(Pet)) && !typeof(Pet).IsAssignableFrom(elementType))
            {
                var value = System.Linq.Expressions.Expression.Parameter(elementType, "value");
                var conversion = System.Linq.Expressions.Expression.Convert(value, typeof(Pet));
                source = System.Linq.Expressions.Expression.Call(
                    typeof(System.Reactive.Linq.Observable),
                    "Select",
                    new System.Type[] { elementType, typeof(Pet) },
                    source,
                    System.Linq.Expressions.Expression.Lambda(conversion, value));
                elementType = typeof(Pet);
            }

            if (returnType.IsAssignableFrom(elementType))
            {
                return System.Linq.Expressions.Expression.Convert(
                    source,
                    typeof(System.IObservable<>).MakeGenericType(returnType));
            }

            var matchType = typeof(Pet).IsAssignableFrom(returnType) ? returnType : typeof(Pet);
            if (!elementType.IsInterface && !elementType.IsAssignableFrom(matchType))
            {
                throw new System.InvalidOperationException(
                    "The input type '" + inputType + "' can never match the type '" + returnType + "'.");
            }

            return System.Linq.Expressions.Expression.Call(
                typeof(MatchPet),
                "Process",
                new System.Type[] { returnType },
                source);
        }

    
        private static System.IObservable<TResult> Process<TResult>(System.IObservable<object> source)
        {
            return System.Reactive.Linq.Observable.Create<TResult>(observer =>
            {
                var sourceObserver = System.Reactive.Observer.Create<object>(
                    value =>
                    {
                        if (value is TResult) observer.OnNext((TResult)value);
                        else
                        {
                            var wrapper = value as IUnionWrapper<TResult>;
                            if (wrapper != null) observer.OnNext(wrapper.Value);
                        }
                    },
                    observer.OnError,
                    observer.OnCompleted);
                return System.ObservableExtensions.SubscribeSafe(source, sourceObserver);
            });
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    internal interface IUnionWrapper
    {
    
        object Value { get; set; }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    public interface IUnionWrapper<out T>
    {
    
        T Value { get; }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    internal class JsonUnionWrapperConverter : Newtonsoft.Json.JsonConverter
    {
    
        readonly System.Type valueType;
        readonly string discriminatorName;
        readonly string discriminatorValue;

        public JsonUnionWrapperConverter(System.Type valueType, string discriminatorName, string discriminatorValue)
        {
            this.valueType = valueType;
            this.discriminatorName = discriminatorName;
            this.discriminatorValue = discriminatorValue;
        }

        public override bool CanConvert(System.Type objectType)
        {
            return true;
        }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            var wrapper = (IUnionWrapper)value;
            var jObject = Newtonsoft.Json.Linq.JObject.FromObject(wrapper.Value, serializer);
            jObject.Remove(discriminatorName);
            jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(discriminatorName, discriminatorValue));
            jObject.WriteTo(writer);
        }

        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var jObject = Newtonsoft.Json.Linq.JObject.Load(reader);
            jObject[discriminatorName] = discriminatorValue;
            var wrapper = (IUnionWrapper)System.Activator.CreateInstance(objectType, true);
            wrapper.Value = jObject.ToObject(valueType, serializer);
            return wrapper;
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.AttributeUsageAttribute(System.AttributeTargets.Class)]
    internal class YamlUnionWrapperAttribute : System.Attribute
    {
    
        public YamlUnionWrapperAttribute(System.Type valueType)
        {
            ValueType = valueType;
        }

        public System.Type ValueType { get; private set; }

    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<Cat> source)
        {
            return Process<Cat>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Pet> source)
        {
            return Process<Pet>(source);
        }

        public System.IObservable<string> Process(System.IObservable<PersonAndPet> source)
        {
            return Process<PersonAndPet>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Cat>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Pet>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PersonAndPet>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<PersonAndPet>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.AttributeUsageAttribute((System.AttributeTargets.Class | System.AttributeTargets.Interface))]
    public class YamlDiscriminatorAttribute : System.Attribute
    {
    
        public YamlDiscriminatorAttribute(string discriminator)
        {
            Discriminator = discriminator;
        }

        public string Discriminator { get; private set; }

    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    public class YamlDiscriminatorTypeInspector : YamlDotNet.Serialization.TypeInspectors.ReflectionTypeInspector
    {
    
        readonly YamlDotNet.Serialization.ITypeInspector innerTypeDescriptor;

        public YamlDiscriminatorTypeInspector(YamlDotNet.Serialization.ITypeInspector innerTypeDescriptor)
        {
            if (innerTypeDescriptor == null)
            {
                throw new System.ArgumentNullException("innerTypeDescriptor");
            }

            this.innerTypeDescriptor = innerTypeDescriptor;
        }

        public override System.Collections.Generic.IEnumerable<YamlDotNet.Serialization.IPropertyDescriptor> GetProperties(System.Type type, object container)
        {
            var innerProperties = innerTypeDescriptor.GetProperties(type, container);

            var discriminatorAttribute = (YamlDiscriminatorAttribute)System.Attribute.GetCustomAttribute(type, typeof(YamlDiscriminatorAttribute));
            var inheritanceAttributes = (JsonInheritanceAttribute[])System.Attribute.GetCustomAttributes(type, typeof(JsonInheritanceAttribute));
            var typeMatch = System.Array.Find(inheritanceAttributes, attribute => attribute.Type == type);
            if (discriminatorAttribute != null && typeMatch != null)
            {
                var unionWrapperAttribute = (YamlUnionWrapperAttribute)System.Attribute.GetCustomAttribute(type, typeof(YamlUnionWrapperAttribute));
                if (unionWrapperAttribute != null)
                {
                    var valueType = unionWrapperAttribute.ValueType;
                    var value = container != null ? ((IUnionWrapper)container).Value : null;
                    innerProperties = System.Linq.Enumerable.Select(
                        System.Linq.Enumerable.Where(
                            innerTypeDescriptor.GetProperties(valueType, value),
                            descriptor => descriptor.Name != discriminatorAttribute.Discriminator),
                        descriptor => (YamlDotNet.Serialization.IPropertyDescriptor)new UnionValuePropertyDescriptor(valueType, descriptor));
                }

                return System.Linq.Enumerable.Concat(new[]
                {
                    new DiscriminatorPropertyDescriptor(discriminatorAttribute.Discriminator, typeMatch.Key)
                }, innerProperties);
            }

            return innerProperties;
        }

        class DiscriminatorPropertyDescriptor : YamlDotNet.Serialization.IPropertyDescriptor
        {
            readonly string key;

            public DiscriminatorPropertyDescriptor(string discriminator, string value)
            {
                ScalarStyle = YamlDotNet.Core.ScalarStyle.Plain;
                Name = discriminator;
                key = value;
            }

            public string Name { get; private set; }

            public bool Required
            {
                get { return true; }
            }

            public bool CanWrite
            {
                get { return true; }
            }

            public System.Type Type
            {
                get { return typeof(string); }
            }

            public System.Type TypeOverride { get; set; }

            public System.Type ConverterType
            {
                get { return null; }
            }

            public bool AllowNulls
            {
                get { return false; }
            }

            public int Order { get; set; }

            public YamlDotNet.Core.ScalarStyle ScalarStyle { get; set; }

            public T GetCustomAttribute<T>() where T : System.Attribute
            {
                return null;
            }

            public YamlDotNet.Serialization.IObjectDescriptor Read(object target)
            {
                return new YamlDotNet.Serialization.ObjectDescriptor(key, Type, Type, ScalarStyle);
            }

            public void Write(object target, object value)
            {
            }
        }

        class UnionValuePropertyDescriptor : YamlDotNet.Serialization.IPropertyDescriptor
        {
            readonly System.Type valueType;
            readonly YamlDotNet.Serialization.IPropertyDescriptor innerDescriptor;

            public UnionValuePropertyDescriptor(System.Type valueType, YamlDotNet.Serialization.IPropertyDescriptor innerDescriptor)
            {
                this.valueType = valueType;
                this.innerDescriptor = innerDescriptor;
            }

            public string Name
            {
                get { return innerDescriptor.Name; }
            }

            public bool Required
            {
                get { return innerDescriptor.Required; }
            }

            public bool CanWrite
            {
                get { return innerDescriptor.CanWrite; }
            }

            public System.Type Type
            {
                get { return innerDescriptor.Type; }
            }

            public System.Type TypeOverride
            {
                get { return innerDescriptor.TypeOverride; }
                set { innerDescriptor.TypeOverride = value; }
            }

            public System.Type ConverterType
            {
                get { return innerDescriptor.ConverterType; }
            }

            public bool AllowNulls
            {
                get { return innerDescriptor.AllowNulls; }
            }

            public int Order
            {
                get { return innerDescriptor.Order; }
                set { innerDescriptor.Order = value; }
            }

            public YamlDotNet.Core.ScalarStyle ScalarStyle
            {
                get { return innerDescriptor.ScalarStyle; }
                set { innerDescriptor.ScalarStyle = value; }
            }

            public T GetCustomAttribute<T>() where T : System.Attribute
            {
                return innerDescriptor.GetCustomAttribute<T>();
            }

            public YamlDotNet.Serialization.IObjectDescriptor Read(object target)
            {
                return innerDescriptor.Read(((IUnionWrapper)target).Value);
            }

            public void Write(object target, object value)
            {
                var wrapper = (IUnionWrapper)target;
                var member = wrapper.Value;
                if (member == null)
                {
                    member = System.Activator.CreateInstance(valueType);
                }
                innerDescriptor.Write(member, value);
                wrapper.Value = member;
            }
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                    .WithTypeInspector(inspector => new YamlDiscriminatorTypeInspector(inspector))
                    .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                    .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<Cat> source)
        {
            return Process<Cat>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Pet> source)
        {
            return Process<Pet>(source);
        }

        public System.IObservable<string> Process(System.IObservable<PersonAndPet> source)
        {
            return Process<PersonAndPet>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.10.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Cat>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Pet>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PersonAndPet>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<PersonAndPet>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static void AddTypeDiscriminator<T>(YamlDotNet.Serialization.BufferedDeserialization.ITypeDiscriminatingNodeDeserializerOptions o)
        {
            var baseType = typeof(T);
            var discriminator = System.Reflection.CustomAttributeExtensions.GetCustomAttribute<YamlDiscriminatorAttribute>(baseType).Discriminator;
            var typeMapping = System.Linq.Enumerable.ToDictionary(
                System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(baseType),
                attr => attr.Key,
                attr => attr.Type);
            o.AddKeyValueTypeDiscriminator<T>(discriminator, typeMapping);
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                    .WithTypeInspector(inspector => new YamlDiscriminatorTypeInspector(inspector))
                    .WithTypeDiscriminatingNodeDeserializer(o =>
                    {
                        AddTypeDiscriminator<Pet>(o);
                    })
                    .EnablePrivateConstructors()
                    .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                    .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}