"""Types covering each schema pattern generated by Bonsai.Sgen."""

from datetime import datetime, timedelta
from typing import Annotated, Literal

from pydantic import Field
from typing_extensions import TypeAliasType

from bonsai.sgen import DiscriminatedUnion, SchemaAlias, SchemaEnum, SchemaModel, SchemaUnion

from . import base

SGEN_NAMESPACE = "TestHelper.Derived"


class Color(SchemaEnum):
    """Specifies the available colors."""

    RED = 1
    DARK_BLUE = 2
    LightGreen = 10


class Mood(str, SchemaEnum):
    """Specifies the available moods."""

    HAPPY = "happy"
    VERY_SAD = "very sad"


class Cat(SchemaModel):
    """A member of several unions."""

    kind: Literal["cat"] = "cat"
    name: str
    lives: int = 9


class Hamster(SchemaModel):
    """A hamster."""

    kind: Literal["hamster"] = "hamster"
    name: str


class Animal(SchemaUnion):
    """A union including a member generated in another namespace."""

    root: Annotated[Cat | base.Dog, Field(discriminator="kind")]


class Pet(SchemaUnion):
    """A union sharing a member with another union."""

    root: Annotated[Cat | Hamster, Field(discriminator="kind")]


class Parrot(SchemaModel):
    """A union member that declares no tag."""

    name: str
    words: int = 0


class Goldfish(SchemaModel):
    """A union member that declares no tag."""

    name: str


class Creature(SchemaUnion):
    """A union assigning the tags of its members."""

    root: Annotated[Parrot | Goldfish, DiscriminatedUnion("species")]


Companion = TypeAliasType(
    "Companion", Annotated[Cat | Hamster, Field(discriminator="kind"), SchemaAlias()]
)
"""A union declared as a type alias."""

Flock = TypeAliasType(
    "Flock", Annotated[Parrot | Goldfish, DiscriminatedUnion("species"), SchemaAlias()]
)
"""A union alias assigning the tags of its members."""


class Home(SchemaModel):
    """A model referring to unions declared as type aliases."""

    companion: Companion
    companions: list[Companion] = []
    flock: Flock | None = None


class Palette(SchemaModel):
    """A choice of colors and moods."""

    color: Color = Color.RED
    favorite: Color | None = None
    mood: Mood = Mood.HAPPY


class Owner(SchemaModel):
    """A model with the common property types."""

    name: str
    age: int | None = None
    weight: float = 0.0
    nicknames: list[str] = []
    animal: Animal
    pets: list[Pet] = []
    friends: dict[str, Cat] = {}
    creature: Creature | None = None


Label = TypeAliasType("Label", str)
"""An alias of a scalar type."""


class Tag(SchemaModel):
    """A model referring to an alias of a scalar type."""

    label: Label


class Visit(SchemaModel):
    """A visit to the veterinarian."""

    start: datetime
    duration: timedelta | None = None
