"""Types covering each schema pattern generated by Bonsai.Sgen."""

from datetime import datetime, timedelta
from typing import Annotated, Literal

from pydantic import Field

from bonsai.sgen import DiscriminatedUnion, SchemaEnum, SchemaModel, SchemaUnion

from . import base

SGEN_NAMESPACE = "TestHelper.Derived"


class Color(SchemaEnum):
    """Specifies the available colors."""

    RED = 1
    DARK_BLUE = 2
    LightGreen = 10


class Mood(str, SchemaEnum):
    """Specifies the available moods."""

    HAPPY = "happy"
    VERY_SAD = "very sad"


class Cat(SchemaModel):
    """A cat, which belongs to two unions."""

    kind: Literal["cat"] = "cat"
    name: str
    lives: int = 9


class Hamster(SchemaModel):
    """A hamster."""

    kind: Literal["hamster"] = "hamster"
    name: str


class Animal(SchemaUnion):
    """An animal, including a member generated in another namespace."""

    root: Annotated[Cat | base.Dog, Field(discriminator="kind")]


class Pet(SchemaUnion):
    """A pet, sharing a member with another union."""

    root: Annotated[Cat | Hamster, Field(discriminator="kind")]


class Parrot(SchemaModel):
    """A parrot, which declares no tag."""

    name: str
    words: int = 0


class Goldfish(SchemaModel):
    """A goldfish, which declares no tag."""

    name: str


class Creature(SchemaUnion):
    """A creature, tagged by the union rather than by its members."""

    root: Annotated[Parrot | Goldfish, DiscriminatedUnion("species")]


class Palette(SchemaModel):
    """A choice of colors and moods."""

    color: Color = Color.RED
    favorite: Color | None = None
    mood: Mood = Mood.HAPPY


class Owner(SchemaModel):
    """An owner of animals, with the common property types."""

    name: str
    age: int | None = None
    weight: float = 0.0
    nicknames: list[str] = []
    animal: Animal
    pets: list[Pet] = []
    friends: dict[str, Cat] = {}
    creature: Creature | None = None


class Visit(SchemaModel):
    """A visit to the veterinarian."""

    start: datetime
    duration: timedelta | None = None
