"""Exports the JSON schema documents from which Bonsai.Sgen generates code."""

import json
from os import PathLike
from pathlib import Path
from types import ModuleType

from pydantic import TypeAdapter
from pydantic.json_schema import JsonSchemaValue

from .schema import (
    TYPENAME_KEY,
    SchemaModel,
    SchemaType,
    SchemaUnion,
    _alias_marker,
    get_typename,
)

_SCALAR_TYPES = frozenset({"boolean", "integer", "number", "string"})
"""JSON types of scalar definitions."""


def _is_scalar(definition: JsonSchemaValue) -> bool:
    return definition.get("type") in _SCALAR_TYPES and "enum" not in definition


def schema_types(module: ModuleType) -> list[SchemaType]:
    """Returns the models, unions and union aliases defined in a module, in declaration order."""
    return [
        value
        for value in vars(module).values()
        if (
            isinstance(value, type)
            and issubclass(value, SchemaModel | SchemaUnion)
            or _alias_marker(value) is not None
        )
        and value.__module__ == module.__name__
    ]


def export_schema(*models: SchemaType) -> JsonSchemaValue:
    """Returns a schema document defining the specified models and every type they refer to.

    The document has no root type, only definitions, including those of types from other
    namespaces. The code generated by Bonsai.Sgen defines only the types in the namespace
    being generated, and refers to any other types by their type names. A discriminated
    union without a type name, such as a type alias not marked with `SchemaAlias`, is
    generated as a local union in every namespace referring to it.

    Union aliases annotated with `SchemaAlias` can be specified alongside models, so that a
    union is defined even if no model in its namespace refers to it.

    Raises:
        TypeError: If a specified type is not a schema type, or a definition has no type
            name, such as a plain pydantic model, enumeration or type alias. Discriminated
            unions are exempt, since they are generated as local unions, and so are aliases
            of scalar types, since they need no type name.
    """
    if not models:
        raise ValueError("No models to export.")
    for model in models:
        get_typename(model)
    _, schema = TypeAdapter.json_schemas(
        [(index, "validation", TypeAdapter(model)) for index, model in enumerate(models)]
    )
    unnamed = [
        key
        for key, definition in schema["$defs"].items()
        if TYPENAME_KEY not in definition
        and "discriminator" not in definition
        and not _is_scalar(definition)
    ]
    if unnamed:
        raise TypeError(
            f"Missing type names for {', '.join(sorted(unnamed))}. Declare these types as "
            "subclasses of SchemaModel, SchemaEnum or SchemaUnion."
        )
    return schema


def write_schema(directory: str | PathLike[str], *models: SchemaType) -> Path:
    """Writes the schema of models in a single namespace to a file.

    The schema file is named after the namespace. Bonsai.Sgen derives both the namespace and
    the name of the generated file from the name of the schema file.

    Returns:
        The path of the schema file.

    Raises:
        ValueError: If the models belong to more than one namespace.
    """
    namespaces = sorted({get_typename(model).rpartition(".")[0] for model in models})
    if len(namespaces) != 1:
        raise ValueError(f"Models belong to {len(namespaces)} namespaces: {namespaces}.")
    path = Path(directory) / f"{namespaces[0]}.json"
    path.write_text(json.dumps(export_schema(*models), indent=2) + "\n", encoding="utf-8")
    return path
